import streamlit as st
import os

current_dir = os.path.dirname(os.path.abspath(__file__))
image_path_1 = os.path.join(current_dir, "../imgs/energy_renewable_logo.png")
image_path_2 = os.path.join(current_dir, "../imgs/tech_logo.png")

def render():
    col1, col2 = st.columns(2)
    with col1:
        # Display the project logo at the top center of the page
        st.image(image_path_1, width=300, use_container_width=False)
    with col2:
        st.image(image_path_2, width=300, use_container_width=False)
    # Add a title for the project
    st.title("Data Science Project - Wind Rose Prediction")

    # Add a description of the project
    st.write(
        """
        Welcome to our Data Science project platform! This application allows you to:

        - **Upload a CSV file** in the **Upload Data** section. Here, you can add datasets for analysis.
            OBS. Your database in csv format must contain the following columns:
            - direccion_viento
            - velocidad_viento
            - presion_barometrica
            - temperatura
        - **Visualize Data** in the **Data Visualization** section, you'll find the data frames of your csv files. 
        - **Visualize Results** in the **Machine Learning** section, where you'll find predictions generated by our models.

        Use this platform to explore insights from your data and leverage advanced predictive models to make informed decisions.
        """
    )
    st.subheader("Data Interpretation")
    st.write("Spanish")
    st.write("""
    Una rosa de vientos es una representación gráfica que muestra la distribución de la dirección y velocidad del viento. 
    - **Dirección**: Cada sector circular representa una dirección (N, NE, E, etc.) desde donde sopla el viento.
    - **Velocidad**: Los colores indican rangos de velocidad del viento según la leyenda.
    - **Interpretación**: La longitud de las barras muestra la frecuencia o intensidad del viento desde cada dirección. Por ejemplo, barras largas con colores claros indican vientos frecuentes y fuertes.
    """, unsafe_allow_html=True)

    st.write("English")
    st.write("""
    A wind rose is a graphical representation that shows the distribution of wind direction and speed. 
    - **Direction**: Each circular sector represents a direction (N, NE, E, etc.) from where the wind blows.
    - **Speed**: The colors indicate ranges of wind speed based on the legend.
    - **Interpretation**: The length of the bars shows the frequency or intensity of wind from each direction. For example, long bars with clear colors indicate frequent and strong winds. 
    """, unsafe_allow_html=True)


    # Add a call-to-action or navigation suggestion
    st.markdown(
        """
        👉 Navigate through the sections using the sidebar to get started!
        """
    )

    # Placeholder for future project content or interaction
    st.write("Feel free to upload your data and explore the predictions.")

